name: dlgm
channels:
  - pytorch
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.2=py37hb5b8e2f_1
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py37_1
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.3.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.36=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - ninja=1.8.2=py37h04f5b5a_1
  - notebook=5.7.6=py37_0
  - numpy=1.16.2=py37hacdab7b_0
  - numpy-base=1.16.2=py37h6575580_0
  - openssl=1.1.1b=h1de35cc_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.4=py37_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.0.3=py37_0
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.3.1=py37_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.14.11=py37h1de35cc_0
  - python=3.7.2=haf84260_0
  - python-dateutil=2.8.0=py37_0
  - pytorch=1.0.1=py3.7_2
  - pyzmq=18.0.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.4.3=py37_0
  - readline=7.0=h1de35cc_5
  - send2trash=1.5.0=py37_0
  - setuptools=40.8.0=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.12.0=py37_0
  - sqlite=3.27.2=ha441bb4_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.1=py37h1de35cc_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.1=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3

